version = 1

test_patterns = [
  "tests/**",
  "test/**",
  "test_*.py"
]

exclude_patterns = [
  "tests/**",
  "test/**",
  "test_*.py"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "isort"