# General Bot Configuration
default_language: "ja"
multi_lang: true
use_informal_lang: true
theme_color: "#2b67ab"
max_note: 500

# Status and Version Information
status_text: "🌟 v6.5.2a"
DEBUG: false

# SQLite Database Configuration
USE_SQLITE: true
SQLITE_PATH: "sqlite/database.db"

# YouTube Metadata Configuration
use_ytdlp: false

# Color Settings for Different Types of Messages
type_color:
  success: [ 157, 255, 158 ]
  error: [ 255, 157, 157 ]
  warn: [ 255, 206, 157 ]
  info: [ 219, 157, 255 ]
  list: [ 157, 200, 255 ]
  win: [ 255, 194, 125 ]
  lose: [ 52, 55, 74 ]
  game: [ 143, 255, 221 ]

# Error and Bug Reporting
error_log_channel_id: 1249810745735118889
bug_report_channel_id: 1265273795544088727

# Owner and Logging Configuration
bot_owner_id: 699452241312219147
enable_activity_logging: false
logging_channel_id: 1203866958487879680

# Game Configuration
jackpot_base_amount: 100000
jackpot_daily_invest: 1000
jackpot_tax_rate: 0.25
jackpot_win_global_announcement: true
handle_jackpot_bet_per_guild: true
