# Default permission for all commands
# You can change the permission for each command in the command's yaml file
# The permission is a string, it can be:
# - "everyone": everyone can use the command
# - "owner": only the bot owner can use the command
# - "admin": only the server admins (with discord's administrator permission) can use the command
# - "mod": only the server mods (with discord's manage server permission) can use the command
# - "disabled": no one can use the command
# To allow multiple permissions, separate them with a comma. For example: "owner,admin"

setting:
    game:
        game_announce_channel: "admin,mod"
    music:
        silent_mode: "admin,mod"
        auto_leave: "admin,mod"
        default_loop_mode: "admin,mod"
    language: "admin,mod"

music:
    music:
        play: "everyone"
        skip: "everyone"
        queue: "everyone"
        shuffle: "everyone"
        loop: "everyone"
        nowplaying: "everyone"
        stop: "everyone"
        pause: "everyone"
        resume: "everyone"
        remove: "everyone"
        register: "everyone"
        most_played: "everyone"

rank:
    rank:
        card: "everyone"
        leaderboard: "everyone"

points:
    point:
        claim: "everyone"
        give: "everyone"
        show: "everyone"
        leaderboard: "everyone"

permission:
    permission:
        list: "admin,mod"
        user: "admin"
        role: "admin"

notes:
    note:
        create: "everyone"
        list: "everyone"
        view: "everyone"
        remove: "everyone"

shop:
    shop:
        catalog: "everyone"
        buy: "everyone"

status:
    ping: "everyone"
    info: "everyone"

bug_report:
    bug: "everyone"