USE_SQLITE: true
SQLITE_PATH: "sqlite/database.db"
DEBUG: false
status_text: "🌟 v6.5.2a"

default_language: "en"
multi_lang: true
use_informal_lang: false

use_ytdlp: false

theme_color: "#2b67ab"
max_note: 500

type_color:
  success: [ 157, 255, 158 ]
  error: [ 255, 157, 157 ]
  warn: [ 255, 206, 157 ]
  info: [ 219, 157, 255 ]
  list: [ 157, 200, 255 ]
  win: [ 255, 194, 125 ]
  lose: [ 52, 55, 74 ]
  game: [ 97, 113, 255 ]

error_log_channel_id: 000000000000000000
bug_report_channel_id: 000000000000000000
bot_owner_id: 000000000000000000

enable_activity_logging: false
logging_channel_id: 000000000000000000
