name: Daily Alpha Release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get current version
        id: get_version
        run: |
          version=$(grep '__version__' version.py | cut -d '"' -f 2)
          echo "Current Version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          version=${{ env.version }}
          IFS='.' read -ra version_parts <<< "$version"
          alpha_number=${version_parts[2]#*-alpha.}
          alpha_number=$((alpha_number + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.0-alpha.${alpha_number}"
          echo "New Version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Debug current version file
        run: |
          cat version.py

      - name: Update version file
        run: |
          new_version=${{ env.new_version }}
          echo "__version__ = \"$new_version\"" > version.py
          cat version.py  # Debugging to check the content
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.py
          git status  # Debugging to check the status of the working directory
          git commit -m "Bump version to $new_version" || echo "No changes to commit"
          git push

      - name: Generate Changelog
        id: generate_changelog
        run: |
          changelog=$(git log --pretty=format:"%h %s" --since="24 hours ago")
          encoded_changelog=$(echo "$changelog" | base64)
          echo "Changelog: $changelog"
          echo "changelog=$encoded_changelog" >> $GITHUB_ENV

      - name: Decode Changelog
        id: decode_changelog
        run: |
          echo "${{ env.changelog }}" | base64 --decode > decoded_changelog.txt
          echo "changelog_body=$(cat decoded_changelog.txt)" >> $GITHUB_ENV

      - name: Create Alpha Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.new_version }}"
          name: "v${{ env.new_version }} - Alpha"
          body: |
            ## Changelog
            ${{ env.changelog_body }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
